require('settings')
-- require('galaxyline-config')
require('feline-config')
require('nvim-tree-config')
require('indent-blankline-config')
require('autopairs-config')
require('cmp-config')
require('lsp')
require('treesitter-config')
require('telescope-config')
require('minimap-config')
require('trouble-config')
require('legendary-config')
require('dressing-config')
require('bufferline-config')
require('gitsigns-config')
